//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuongMaiDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMENT_PRODUCT
    {
        public int IdComment { get; set; }
        public string CommentContent { get; set; }
        public int IdProduct { get; set; }
        public int IdCustomer { get; set; }
        public Nullable<bool> CommentStatus { get; set; }
        public int IdUser { get; set; }
        public Nullable<System.DateTime> CommentDate { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual CUSTOMER CUSTOMER1 { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual PRODUCT PRODUCT1 { get; set; }
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
    }
}
