//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuongMaiDienTu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class THUONGMAIDIENTUEntities : DbContext
    {
        public THUONGMAIDIENTUEntities()
            : base("name=THUONGMAIDIENTUEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATEGORY_NEWS> CATEGORY_NEWS { get; set; }
        public virtual DbSet<CATEGORY_PRODUCT> CATEGORY_PRODUCT { get; set; }
        public virtual DbSet<COMMENT_PRODUCT> COMMENT_PRODUCT { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public virtual DbSet<GIFTCODE> GIFTCODEs { get; set; }
        public virtual DbSet<INFO> INFOes { get; set; }
        public virtual DbSet<NEWS> NEWS { get; set; }
        public virtual DbSet<ORDER> ORDERs { get; set; }
        public virtual DbSet<ORDER_HISTORY> ORDER_HISTORY { get; set; }
        public virtual DbSet<PAYMENT_METHOD> PAYMENT_METHOD { get; set; }
        public virtual DbSet<PAYMENT_STATUS> PAYMENT_STATUS { get; set; }
        public virtual DbSet<PRODUCT> PRODUCTs { get; set; }
        public virtual DbSet<PRODUCT_IMG> PRODUCT_IMG { get; set; }
        public virtual DbSet<PRODUCT_INFO> PRODUCT_INFO { get; set; }
        public virtual DbSet<PRODUCT_ORDER> PRODUCT_ORDER { get; set; }
        public virtual DbSet<PRODUCT_PROMOTION> PRODUCT_PROMOTION { get; set; }
        public virtual DbSet<PROMOTION> PROMOTIONs { get; set; }
        public virtual DbSet<REVIEW_PRODUCT> REVIEW_PRODUCT { get; set; }
        public virtual DbSet<ROLE> ROLEs { get; set; }
        public virtual DbSet<USER> USERs { get; set; }
    
        public virtual ObjectResult<string> proc_CryptData(string data)
        {
            var dataParameter = data != null ?
                new ObjectParameter("Data", data) :
                new ObjectParameter("Data", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("proc_CryptData", dataParameter);
        }
    }
}
