//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuongMaiDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDER()
        {
            this.ORDER_HISTORY = new HashSet<ORDER_HISTORY>();
            this.ORDER_HISTORY1 = new HashSet<ORDER_HISTORY>();
            this.PRODUCT_ORDER = new HashSet<PRODUCT_ORDER>();
            this.PRODUCT_ORDER1 = new HashSet<PRODUCT_ORDER>();
        }
    
        public int IdOrder { get; set; }
        public Nullable<int> IdCode { get; set; }
        public int IdCustomer { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<System.DateTime> DateOrder { get; set; }
        public Nullable<System.DateTime> DateDelivery { get; set; }
        public byte[] TimeDelivery { get; set; }
        public Nullable<double> Total { get; set; }
        public string OrderComment { get; set; }
        public int IdPayment { get; set; }
        public int IdStatus { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual CUSTOMER CUSTOMER1 { get; set; }
        public virtual GIFTCODE GIFTCODE { get; set; }
        public virtual GIFTCODE GIFTCODE1 { get; set; }
        public virtual PAYMENT_METHOD PAYMENT_METHOD { get; set; }
        public virtual PAYMENT_METHOD PAYMENT_METHOD1 { get; set; }
        public virtual PAYMENT_STATUS PAYMENT_STATUS { get; set; }
        public virtual PAYMENT_STATUS PAYMENT_STATUS1 { get; set; }
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_HISTORY> ORDER_HISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_HISTORY> ORDER_HISTORY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT_ORDER> PRODUCT_ORDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT_ORDER> PRODUCT_ORDER1 { get; set; }
    }
}
