//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuongMaiDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_PROMOTION
    {
        public int IdProduct { get; set; }
        public int IdPromotion { get; set; }
        public Nullable<double> Discount { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual PRODUCT PRODUCT1 { get; set; }
        public virtual PROMOTION PROMOTION { get; set; }
        public virtual PROMOTION PROMOTION1 { get; set; }
    }
}
