//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuongMaiDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROMOTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROMOTION()
        {
            this.PRODUCT_PROMOTION = new HashSet<PRODUCT_PROMOTION>();
            this.PRODUCT_PROMOTION1 = new HashSet<PRODUCT_PROMOTION>();
        }
    
        public int IdPromotion { get; set; }
        public string PromotionName { get; set; }
        public Nullable<System.DateTime> PromotionStart { get; set; }
        public Nullable<System.DateTime> PromotionEnd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT_PROMOTION> PRODUCT_PROMOTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT_PROMOTION> PRODUCT_PROMOTION1 { get; set; }
    }
}
